// These are macros designed to help with metal implementation

#ifdef NT_MTL_SUPPORTED
#ifndef NS_PRIVATE_IMPLEMENTATION
#define NS_PRIVATE_IMPLEMENTATION
#endif
#ifndef MTL_PRIVATE_IMPLEMENTATION 
#define MTL_PRIVATE_IMPLEMENTATION
#endif
#ifndef MTK_PRIVATE_IMPLEMENTATION
#define MTK_PRIVATE_IMPLEMENTATION
#endif
#ifndef CA_PRIVATE_IMPLEMENTATION 
#define CA_PRIVATE_IMPLEMENTATION
#endif
#endif
