set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER musl-gcc)
set(CMAKE_CXX_COMPILER musl-g++)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_EXE_LINKER_FLAGS "-static -static-libstdc++")


