name: Build and Package NeuroTensor (Windows Only)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version (e.g., v1.2.3)"
        required: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - nt_core
          - nt_types
          - nt_functional
          - nt_functional_cpu
          - nt_matmult
          - nt_linalg
          - nt_svd
          - nt_qr
          - nt_inv
          - nt_column_space
          - nt_null_space
          - nt_ai
          - nt_tda
          - nt_sparse
          - nt_images
          - nt_memory
          - nt_multi_processing
          - nt_fmri

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore build/ directory cache
        uses: actions/cache@v4
        with:
          path: build/
          key: neurotensor-win-build-${{ matrix.target }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            neurotensor-win-build-${{ matrix.target }}-

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=install
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          -DBUILD_MAIN=OFF
      
      - name: Build target ${{ matrix.target }} if not already built
        shell: cmd
        run: |
          if not exist build\\.built_${{ matrix.target }} (
            cmake --build build --target ${{ matrix.target }} --config Release
            echo done > build\\.built_${{ matrix.target }}
          )

      - name: Save updated build cache
        uses: actions/cache/save@v4
        with:
          path: build/
          key: neurotensor-win-build-${{ matrix.target }}-${{ github.run_id }}

    
  package:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create build directory
        run: mkdir -p build
  
      - name: Restore nt_core build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_core/
          key: neurotensor-win-build-nt_core-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_core-



      - name: Restore nt_types build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_types/
          key: neurotensor-win-build-nt_types-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_types-



      - name: Restore nt_functional build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_functional/
          key: neurotensor-win-build-nt_functional-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_functional-



      - name: Restore nt_functional_cpu build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_functional_cpu/
          key: neurotensor-win-build-nt_functional_cpu-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_functional_cpu-



      - name: Restore nt_matmult build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_matmult/
          key: neurotensor-win-build-nt_matmult-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_matmult-



      - name: Restore nt_linalg build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_linalg/
          key: neurotensor-win-build-nt_linalg-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_linalg-



      - name: Restore nt_svd build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_svd/
          key: neurotensor-win-build-nt_svd-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_svd-



      - name: Restore nt_qr build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_qr/
          key: neurotensor-win-build-nt_qr-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_qr-



      - name: Restore nt_inv build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_inv/
          key: neurotensor-win-build-nt_inv-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_inv-



      - name: Restore nt_column_space build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_column_space/
          key: neurotensor-win-build-nt_column_space-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_column_space-



      - name: Restore nt_null_space build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_null_space/
          key: neurotensor-win-build-nt_null_space-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_null_space-



      - name: Restore nt_ai build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_ai/
          key: neurotensor-win-build-nt_ai-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_ai-



      - name: Restore nt_tda build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_tda/
          key: neurotensor-win-build-nt_tda-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_tda-



      - name: Restore nt_sparse build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_sparse/
          key: neurotensor-win-build-nt_sparse-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_sparse-



      - name: Restore nt_images build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_images/
          key: neurotensor-win-build-nt_images-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_images-



      - name: Restore nt_memory build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_memory/
          key: neurotensor-win-build-nt_memory-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_memory-



      - name: Restore nt_multi_processing build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_multi_processing/
          key: neurotensor-win-build-nt_multi_processing-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_multi_processing-



      - name: Restore nt_fmri build cache
        uses: actions/cache@v4
        with:
          path: temp/nt_fmri/
          key: neurotensor-win-build-nt_fmri-${ github.run_id }
          restore-keys: neurotensor-win-build-nt_fmri-

      - name: Combine build directories
        shell: pwsh
        run: |
          $targets = @(
            'nt_core', 'nt_types', 'nt_functional', 'nt_functional_cpu',
            'nt_matmult', 'nt_linalg', 'nt_svd', 'nt_qr', 'nt_inv',
            'nt_column_space', 'nt_null_space', 'nt_ai', 'nt_tda',
            'nt_sparse', 'nt_images', 'nt_memory', 'nt_multi_processing', 'nt_fmri'
          )

          foreach ($target in $targets) {
            $source = "temp/$target/build"
            if (Test-Path $source) {
              Write-Host "Merging $source into build/"
              Copy-Item -Path "$source\*" -Destination build/ -Recurse -Force
            }
          }

      - name: Configure CMake if needed
        shell: cmd
        run: |
          if not exist build/CMakeCache.txt (
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_MAIN=OFF
          )

      - name: Build neurotensor only
        run: cmake --build build --target neurotensor --config Release

      - name: Install
        run: cmake --install build --prefix package-out

      - name: Archive package
        run: |
          powershell -Command "Compress-Archive -Path package-out\* -DestinationPath neurotensor-windows-x86_64-${{ github.event.inputs.version }}.zip"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "NeuroTensor ${{ github.event.inputs.version }}"
          files: neurotensor-windows-x86_64-${{ github.event.inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

