name: Build and Package NeuroTensor clang (Ubuntu x86_64)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version (e.g., v1.2.3)"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      

      - name: Configure (musl, static)
        run: >
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build neurotensor with musl
        run: cmake --build build --target neurotensor --config Release

      - name: Check neurotensor symbols
        run: nm -s build/libneurotensor.a || true

      - name: Install NeuroTensor (headers + lib)
        run: cmake --install build --prefix package-out

      - name: Archive static package
        run: |
          cd package-out
          tar -czvf ../neurotensor-static-clang-${{ github.event.inputs.version }}.tar.gz *

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "NeuroTensor ${{ github.event.inputs.version }}"
          files: neurotensor-ubuntu_x86_64-clang-${{ github.event.inputs.version }}.tar.gz
          overwrite: true
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

